kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
  name: {{ include "tool-config.name" . }}
  labels:
    app: {{ include "tool-config.name" . }}
    app.kubernetes.io/instance: {{ include "tool-config.name" . }}
spec:
  rules:
    - host: {{.Values.hostname}}
      http:
        paths:
          - path: /
            backend:
              serviceName: tekton-dashboard
              servicePort: 9097