{{- if and .Values.username .Values.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tool-config.secret-name" . }}
  labels:
    app.kubernetes.io/name: {{ include "tool-config.name" . }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/part-of: {{ .Values.app }}
    app.kubernetes.io/component: {{ .Values.component }}
    chart: {{ include "tool-config.chart" . }}
    release: {{ .Release.Name }}
    group: {{ .Values.group }}
  annotations:
    description: {{ printf "Secret to hold the username and password for %s so that other components can access it" (include "tool-config.name" .) }}
type: Opaque
stringData:
  {{ include "tool-config.NAME" . }}_PASSWORD: {{ .Values.username | quote }}
  {{ include "tool-config.NAME" . }}_USER: {{ .Values.password | quote }}
{{- end }}
